spark-master:
    image: spark-2
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8079:8079
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data  
spark-worker-1:
    image: spark-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/tmp/data
spark-worker-2:
    image: spark-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    links:
      - spark-master
    expose:
      - 7022
      - 7023
      - 7024
      - 7025
      - 7026
      - 8882
    ports:
      - 8082:8082
    volumes:
      - ./conf/spark-worker-2:/conf
      - ./data:/tmp/data
spark-worker-3:
    image: spark-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-3
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8883
      SPARK_WORKER_WEBUI_PORT: 8083
    links:
      - spark-master
    expose:
      - 7032
      - 7033
      - 7034
      - 7035
      - 7036
      - 8883
    ports:
      - 8083:8083
    volumes:
      - ./conf/spark-worker-3:/conf
      - ./data:/tmp/data
zeppelin:
    image: zeppelin
    command: bash -c "bin/zeppelin-daemon.sh start && tail -f /usr/local/zeppelin-0.6.2-bin-all/logs/zeppelin*.log"
    hostname: zeppelin
    environment:
      MASTER: spark://spark-master:7077
      ZEPPELIN_PORT: 8080
    links:
      - spark-master
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./data:/tmp/data
    tty: true
    stdin_open: true
